### PR TITLE
support for building on macOS

### PR DESCRIPTION
**Pull request by withzombies**
dwarfexport is pretty neat. I took some time to get it building on macOS.

Let me know if you want anything updated.

### CODE REVIEW

**Comment by ALSchwalm** [comment]
Awesome! Thanks for the pr. 

This looks good, but could you add a pre-compiled build to bin? I don't really want to require people to download the SDK and get the elf/dwarf dependencies to test this out. Also, is it possible to get the necessary libs through one of the popular OSX package managers? If not, that's fine, but if so, I'd like to mention it.

**Comment by withzombies** [comment]
Most `brew`packages only build 64bit binaries, as macOS has been 64bit-only for quite awhile now. Building the dependencies yourself and specifying the `-m32` flag is the easiest way to do it. Sadly.

With IDA 7.0 moving to a 64bit executable, a lot of these issues will fixed, but for now this is the best way.

**Comment by withzombies** [comment]
I updated the PR to include the macos binaries.

**Comment by ALSchwalm** [comment]
Gotcha, thanks again for the pr

**Pull request merged**
